// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0yPB4HjX4QdrbhYppL9t_5vyCl_WNwqU',
    appId: '1:1091657055881:web:21d08fe3c4aa838d1ad058',
    messagingSenderId: '1091657055881',
    projectId: 'creditkarnet',
    authDomain: 'creditkarnet.firebaseapp.com',
    storageBucket: 'creditkarnet.firebasestorage.app',
    measurementId: 'G-MFP5G36E2M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQxqZoF_fBXl95IWyHnVWKx5x32YnQzuU',
    appId: '1:1091657055881:android:bad3eeb59a9894121ad058',
    messagingSenderId: '1091657055881',
    projectId: 'creditkarnet',
    storageBucket: 'creditkarnet.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDADxpl9OnLO4l730mzsbAuxrZZJDgQCGc',
    appId: '1:1091657055881:ios:d7fb66a6a26873291ad058',
    messagingSenderId: '1091657055881',
    projectId: 'creditkarnet',
    storageBucket: 'creditkarnet.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDADxpl9OnLO4l730mzsbAuxrZZJDgQCGc',
    appId: '1:1091657055881:ios:d7fb66a6a26873291ad058',
    messagingSenderId: '1091657055881',
    projectId: 'creditkarnet',
    storageBucket: 'creditkarnet.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0yPB4HjX4QdrbhYppL9t_5vyCl_WNwqU',
    appId: '1:1091657055881:web:df82a28eda2986601ad058',
    messagingSenderId: '1091657055881',
    projectId: 'creditkarnet',
    authDomain: 'creditkarnet.firebaseapp.com',
    storageBucket: 'creditkarnet.firebasestorage.app',
    measurementId: 'G-JMVR4T1LL3',
  );

}