// lib/firebase_init.dart
// Firebase initialization and configuration

import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Generated by FlutterFire

/// Initialize Firebase
/// Call this in main() before running the app
Future<void> initializeFirebase() async {
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
}

// ═══════════════════════════════════════════════════════════════════════════
//  UPDATED main.dart
// ═══════════════════════════════════════════════════════════════════════════

/*
import 'package:flutter/material.dart';
import 'firebase_init.dart';
import 'services/app_settings_service.dart';
import 'services/sync_service.dart';
import 'utils/app_translations.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  // 1. Initialize Firebase FIRST
  await initializeFirebase();
  
  // 2. Initialize app settings
  await AppSettingsService.instance.initialize();
  
  // 3. Initialize sync service (already a singleton)
  SyncService.instance;

  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  final _appSettingsSvc = AppSettingsService.instance;

  @override
  void initState() {
    super.initState();
    _appSettingsSvc.addListener(_refresh);
  }

  @override
  void dispose() {
    _appSettingsSvc.removeListener(_refresh);
    super.dispose();
  }

  void _refresh() => setState(() {});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      // ... your app configuration ...
      themeMode: _getThemeMode(),
      theme: ThemeData(
        useMaterial3: true,
        brightness: Brightness.light,
      ),
      darkTheme: ThemeData(
        useMaterial3: true,
        brightness: Brightness.dark,
      ),
      // ... rest of your config ...
    );
  }

  ThemeMode _getThemeMode() {
    switch (_appSettingsSvc.themeMode) {
      case 'light':
        return ThemeMode.light;
      case 'dark':
        return ThemeMode.dark;
      default:
        return ThemeMode.system;
    }
  }
}
*/